# Generated by Django 6.1 on 2026-08-14 09:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('App_Atendimentos', '0001_initial'),
        ('App_Farmacia', '0001_initial'),
        ('App_Hospital', '0001_initial'),
        ('App_Pacientes', '0003_paciente_entidade_vinculada'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PrescricaoMedicamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('AGUARDANDO', 'Aguardando'), ('EM_ANALISE', 'Em análise'), ('EM_SEPARACAO', 'Em separação'), ('AGUARDANDO_CONFERENCIA', 'Aguardando conferência'), ('DISPENSADO', 'Dispensado'), ('PENDENCIA', 'Pendência'), ('CANCELADO', 'Cancelado')], default='AGUARDANDO', max_length=25, verbose_name='Estado')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('atendimento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prescricoes', to='App_Atendimentos.atendimento', verbose_name='Atendimento')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prescricoes', to='App_Hospital.hospital', verbose_name='Hospital')),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prescricoes_emitidas', to=settings.AUTH_USER_MODEL, verbose_name='Médico')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prescricoes', to='App_Pacientes.paciente', verbose_name='Paciente')),
            ],
            options={
                'verbose_name': 'Prescrição de Medicamento',
                'verbose_name_plural': 'Prescrições de Medicamentos',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='ItemPrescricao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dosagem', models.CharField(blank=True, help_text='Ex.: 500mg, 1 cápsula', max_length=50, verbose_name='Dosagem')),
                ('via_administracao', models.CharField(choices=[('ORAL', 'Oral'), ('INTRAVENOSA', 'Intravenosa'), ('INTRAMUSCULAR', 'Intramuscular'), ('SUBCUTANEA', 'Subcutânea'), ('TOPICA', 'Tópica'), ('INALATORIA', 'Inalatória'), ('RECTAL', 'Rectal'), ('OUTRA', 'Outra')], default='ORAL', max_length=20, verbose_name='Via de administração')),
                ('frequencia', models.CharField(blank=True, help_text='Ex.: 8/8h, 1x ao dia', max_length=50, verbose_name='Frequência')),
                ('duracao_dias', models.PositiveIntegerField(blank=True, null=True, verbose_name='Duração (dias)')),
                ('quantidade', models.PositiveIntegerField(verbose_name='Quantidade total prescrita')),
                ('observacoes', models.CharField(blank=True, max_length=255, verbose_name='Observações')),
                ('medicamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='itens_prescritos', to='App_Farmacia.medicamento', verbose_name='Medicamento')),
                ('prescricao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='App_Prescricoes.prescricaomedicamento', verbose_name='Prescrição')),
            ],
            options={
                'verbose_name': 'Item de Prescrição',
                'verbose_name_plural': 'Itens de Prescrição',
            },
        ),
    ]
