# Generated by Django 6.1 on 2026-08-17 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('App_Hospital', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Ex.: Nave A, Pediatria, Maternidade', max_length=100, verbose_name='Nome')),
                ('descricao', models.CharField(blank=True, max_length=255, verbose_name='Descrição')),
                ('ativa', models.BooleanField(default=True, verbose_name='Activa')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='naves', to='App_Hospital.hospital', verbose_name='Hospital')),
            ],
            options={
                'verbose_name': 'Nave',
                'verbose_name_plural': 'Naves',
                'ordering': ['nome'],
                'unique_together': {('hospital', 'nome')},
            },
        ),
        migrations.CreateModel(
            name='Quarto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20, verbose_name='Número do Quarto')),
                ('tipo', models.CharField(choices=[('ENFERMARIA', 'Enfermaria'), ('INDIVIDUAL', 'Individual'), ('UCI', 'UCI / Cuidados Intensivos'), ('ISOLAMENTO', 'Isolamento'), ('OUTRO', 'Outro')], default='ENFERMARIA', max_length=20, verbose_name='Tipo')),
                ('capacidade', models.PositiveIntegerField(verbose_name='Capacidade (nº de internantes)')),
                ('ativo', models.BooleanField(default=True, verbose_name='Activo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('nave', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quartos', to='App_Internamento.nave', verbose_name='Nave')),
            ],
            options={
                'verbose_name': 'Quarto',
                'verbose_name_plural': 'Quartos',
                'ordering': ['nave__nome', 'numero'],
                'unique_together': {('nave', 'numero')},
            },
        ),
    ]
