# Generated by Django 6.1 on 2026-08-17 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Internamento', '0001_initial'),
        ('App_Pacientes', '0003_paciente_entidade_vinculada'),
    ]

    operations = [
        migrations.CreateModel(
            name='Internamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_entrada', models.DateTimeField(auto_now_add=True, verbose_name='Data de entrada')),
                ('data_alta', models.DateTimeField(blank=True, null=True, verbose_name='Data de alta')),
                ('status', models.CharField(choices=[('INTERNADO', 'Internado'), ('ALTA', 'Alta'), ('TRANSFERIDO', 'Transferido'), ('CANCELADO', 'Cancelado')], default='INTERNADO', max_length=20, verbose_name='Estado')),
                ('motivo', models.TextField(blank=True, verbose_name='Motivo do internamento')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='internamentos', to='App_Pacientes.paciente', verbose_name='Paciente')),
                ('quarto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='internamentos', to='App_Internamento.quarto', verbose_name='Quarto')),
            ],
            options={
                'verbose_name': 'Internamento',
                'verbose_name_plural': 'Internamentos',
                'ordering': ['-data_entrada'],
            },
        ),
    ]
