# Generated by Django 6.1 on 2026-08-18 09:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Atendimentos', '0002_consulta'),
        ('App_Hospital', '0001_initial'),
        ('App_Internamento', '0002_internamento'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='internamento',
            name='atendimento',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='internamento', to='App_Atendimentos.atendimento', verbose_name='Atendimento'),
        ),
        migrations.AddField(
            model_name='internamento',
            name='hospital',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='internamentos', to='App_Hospital.hospital', verbose_name='Hospital'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='internamento',
            name='medico_responsavel',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='internamentos_responsavel', to=settings.AUTH_USER_MODEL, verbose_name='Médico Responsável'),
            preserve_default=False,
        ),
    ]
