# Generated by Django 6.1 on 2026-08-18 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Atendimentos', '0002_consulta'),
        ('App_Internamento', '0003_internamento_atendimento_internamento_hospital_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internamento',
            name='atendimento',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='internamento', to='App_Atendimentos.atendimento', verbose_name='Atendimento'),
        ),
    ]
