# Generated by Django 6.1 on 2026-08-20 10:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Internamento', '0004_alter_internamento_atendimento'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Evolucao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('MEDICA', 'Evolução Médica'), ('ENFERMAGEM', 'Evolução de Enfermagem'), ('OUTRA', 'Outra')], max_length=20, verbose_name='Tipo')),
                ('texto', models.TextField(verbose_name='Nota de Evolução')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('internamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evolucoes', to='App_Internamento.internamento', verbose_name='Internamento')),
                ('profissional', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evolucoes_registadas', to=settings.AUTH_USER_MODEL, verbose_name='Profissional')),
            ],
            options={
                'verbose_name': 'Evolução',
                'verbose_name_plural': 'Evoluções',
                'ordering': ['-criado_em'],
            },
        ),
    ]
