# Generated by Django 6.0.7 on 2026-08-10 13:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('App_Agendamentos', '0001_initial'),
        ('App_Hospital', '0001_initial'),
        ('App_Pacientes', '0002_perfil_permissao_perfilpermissao'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoExame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome')),
                ('codigo', models.CharField(max_length=30, unique=True, verbose_name='Código')),
                ('categoria', models.CharField(choices=[('hematologia', 'Hematologia'), ('bioquimica', 'Bioquímica'), ('microbiologia', 'Microbiologia'), ('imunologia', 'Imunologia'), ('uroanalise', 'Uroanálise'), ('parasitologia', 'Parasitologia'), ('hormonal', 'Hormonal'), ('outro', 'Outro')], default='outro', max_length=20, verbose_name='Categoria')),
                ('tipo_amostra', models.CharField(choices=[('sangue', 'Sangue'), ('urina', 'Urina'), ('fezes', 'Fezes'), ('escarro', 'Escarro'), ('swab', 'Swab'), ('liquido_corporal', 'Líquido Corporal'), ('outro', 'Outro')], default='sangue', max_length=20, verbose_name='Tipo de Amostra')),
                ('preparo_necessario', models.TextField(blank=True, help_text='Ex.: jejum de 8 horas, suspender medicação X, etc.', verbose_name='Preparo Necessário')),
                ('tempo_estimado_horas', models.PositiveIntegerField(default=24, verbose_name='Tempo Estimado (horas)')),
                ('valores_referencia', models.TextField(blank=True, verbose_name='Valores de Referência')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Tipo de Exame',
                'verbose_name_plural': 'Tipos de Exame',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Amostra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Código/etiqueta de identificação da amostra (ex.: código de barras).', max_length=40, unique=True, verbose_name='Código da Amostra')),
                ('tipo_amostra', models.CharField(choices=[('sangue', 'Sangue'), ('urina', 'Urina'), ('fezes', 'Fezes'), ('escarro', 'Escarro'), ('swab', 'Swab'), ('liquido_corporal', 'Líquido Corporal'), ('outro', 'Outro')], max_length=20, verbose_name='Tipo de Amostra')),
                ('local_colheita', models.CharField(choices=[('laboratorio', 'Laboratório'), ('domicilio', 'Domicílio')], default='laboratorio', max_length=15, verbose_name='Local da Colheita')),
                ('colhida_em', models.DateTimeField(blank=True, null=True, verbose_name='Colhida em')),
                ('condicao', models.CharField(choices=[('adequada', 'Adequada'), ('inadequada', 'Inadequada'), ('pendente', 'Pendente de Avaliação')], default='pendente', max_length=15, verbose_name='Condição da Amostra')),
                ('motivo_rejeicao', models.TextField(blank=True, verbose_name='Motivo de Rejeição')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('colhida_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='amostras_colhidas', to=settings.AUTH_USER_MODEL, verbose_name='Colhida por')),
            ],
            options={
                'verbose_name': 'Amostra',
                'verbose_name_plural': 'Amostras',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='Requisicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suspeita_clinica', models.CharField(blank=True, max_length=255, verbose_name='Suspeita Clínica')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('status', models.CharField(choices=[('aguardando_colheita', 'Aguardando Colheita'), ('em_colheita', 'Em Colheita'), ('em_analise', 'Em Análise'), ('concluida', 'Concluída'), ('liberada', 'Liberada'), ('cancelada', 'Cancelada')], default='aguardando_colheita', max_length=20, verbose_name='Status')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('agendamento', models.ForeignKey(blank=True, help_text='Consulta médica que originou o pedido de exames, se aplicável.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requisicoes_laboratorio', to='App_Agendamentos.agendamento', verbose_name='Consulta de Origem')),
                ('criado_por', models.ForeignKey(help_text='Profissional que fez a triagem/receção do paciente.', on_delete=django.db.models.deletion.PROTECT, related_name='requisicoes_triadas', to=settings.AUTH_USER_MODEL, verbose_name='Registado por')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requisicoes_laboratorio', to='App_Hospital.hospital', verbose_name='Hospital')),
                ('medico_solicitante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requisicoes_solicitadas', to=settings.AUTH_USER_MODEL, verbose_name='Médico Solicitante')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requisicoes_laboratorio', to='App_Pacientes.paciente', verbose_name='Paciente')),
            ],
            options={
                'verbose_name': 'Requisição de Exames',
                'verbose_name_plural': 'Requisições de Exames',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='LivroSaida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entregue_em', models.DateTimeField(auto_now_add=True, verbose_name='Entregue em')),
                ('recebido_por', models.CharField(help_text='Nome de quem retirou o resultado (paciente ou responsável).', max_length=150, verbose_name='Recebido por')),
                ('documento_recebedor', models.CharField(blank=True, max_length=50, verbose_name='Documento de Identificação')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('entregue_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entregas_realizadas', to=settings.AUTH_USER_MODEL, verbose_name='Entregue por')),
                ('requisicao', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='livro_saida', to='App_Laboratorio.requisicao', verbose_name='Requisição')),
            ],
            options={
                'verbose_name': 'Registo de Saída',
                'verbose_name_plural': 'Livro de Saídas',
                'ordering': ['-entregue_em'],
            },
        ),
        migrations.CreateModel(
            name='ExameSolicitado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('aguardando_colheita', 'Aguardando Colheita'), ('coletado', 'Coletado'), ('em_analise', 'Em Análise'), ('concluido', 'Concluído'), ('liberado', 'Liberado'), ('rejeitado', 'Rejeitado'), ('cancelado', 'Cancelado')], default='aguardando_colheita', max_length=20, verbose_name='Status')),
                ('data_inicio_analise', models.DateTimeField(blank=True, null=True, verbose_name='Início da Análise')),
                ('data_conclusao_analise', models.DateTimeField(blank=True, null=True, verbose_name='Conclusão da Análise')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('amostra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exames', to='App_Laboratorio.amostra', verbose_name='Amostra')),
                ('tecnico_responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exames_processados', to=settings.AUTH_USER_MODEL, verbose_name='Técnico Responsável')),
                ('requisicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exames_solicitados', to='App_Laboratorio.requisicao', verbose_name='Requisição')),
                ('tipo_exame', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitacoes', to='App_Laboratorio.tipoexame', verbose_name='Exame')),
            ],
            options={
                'verbose_name': 'Exame Solicitado',
                'verbose_name_plural': 'Exames Solicitados',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.AddField(
            model_name='amostra',
            name='requisicao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amostras', to='App_Laboratorio.requisicao', verbose_name='Requisição'),
        ),
        migrations.CreateModel(
            name='Resultado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valores', models.TextField(help_text='Resultado bruto do exame (valores, parâmetros, unidades).', verbose_name='Valores Encontrados')),
                ('interpretacao', models.TextField(blank=True, verbose_name='Interpretação/Observações')),
                ('arquivo_laudo', models.FileField(blank=True, null=True, upload_to='laboratorio/laudos/', verbose_name='Laudo (PDF)')),
                ('data_liberacao', models.DateTimeField(blank=True, null=True, verbose_name='Data de Liberação')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('exame_solicitado', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='resultado', to='App_Laboratorio.examesolicitado', verbose_name='Exame Solicitado')),
                ('tecnico_responsavel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='resultados_lancados', to=settings.AUTH_USER_MODEL, verbose_name='Lançado por')),
                ('validado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resultados_validados', to=settings.AUTH_USER_MODEL, verbose_name='Validado por')),
            ],
            options={
                'verbose_name': 'Resultado',
                'verbose_name_plural': 'Resultados',
                'ordering': ['-criado_em'],
            },
        ),
    ]
