# Generated by Django 6.1 on 2026-08-17 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Laboratorio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tipoexame',
            name='preparo_necessario',
        ),
        migrations.RemoveField(
            model_name='tipoexame',
            name='valores_referencia',
        ),
        migrations.AddField(
            model_name='tipoexame',
            name='unidade_medida',
            field=models.CharField(blank=True, help_text='Ex.: mg/dL, g/dL, x10⁹/L', max_length=30, verbose_name='Unidade de medida'),
        ),
        migrations.AddField(
            model_name='tipoexame',
            name='valor_referencia',
            field=models.CharField(blank=True, help_text="Ex.: 4.5 - 11.0, ou 'Negativo' para exames qualitativos", max_length=150, verbose_name='Valor de referência'),
        ),
        migrations.AlterField(
            model_name='amostra',
            name='tipo_amostra',
            field=models.CharField(choices=[('SANGUE', 'Sangue'), ('URINA', 'Urina'), ('FEZES', 'Fezes'), ('SORO', 'Soro'), ('PLASMA', 'Plasma'), ('SECRECAO', 'Secreção'), ('LIQUOR', 'Líquor'), ('OUTRA', 'Outra')], max_length=20, verbose_name='Tipo de Amostra'),
        ),
        migrations.AlterField(
            model_name='tipoexame',
            name='ativo',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='tipoexame',
            name='categoria',
            field=models.CharField(choices=[('HEMATOLOGIA', 'Hematologia'), ('BIOQUIMICA', 'Bioquímica'), ('MICROBIOLOGIA', 'Microbiologia'), ('IMUNOLOGIA', 'Imunologia'), ('UROANALISE', 'Uroanálise'), ('PARASITOLOGIA', 'Parasitologia'), ('HORMONAL', 'Hormonal'), ('OUTRO', 'Outro')], max_length=20, verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='tipoexame',
            name='nome',
            field=models.CharField(max_length=150, verbose_name='Nome do exame'),
        ),
        migrations.AlterField(
            model_name='tipoexame',
            name='tempo_estimado_horas',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Tempo estimado de resultado (horas)'),
        ),
        migrations.AlterField(
            model_name='tipoexame',
            name='tipo_amostra',
            field=models.CharField(choices=[('SANGUE', 'Sangue'), ('URINA', 'Urina'), ('FEZES', 'Fezes'), ('SORO', 'Soro'), ('PLASMA', 'Plasma'), ('SECRECAO', 'Secreção'), ('LIQUOR', 'Líquor'), ('OUTRA', 'Outra')], max_length=20, verbose_name='Tipo de amostra'),
        ),
    ]
