# Generated by Django 6.1 on 2026-08-17 13:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Atendimentos', '0002_consulta'),
        ('App_Hospital', '0001_initial'),
        ('App_Laboratorio', '0002_remove_tipoexame_preparo_necessario_and_more'),
        ('App_Pacientes', '0003_paciente_entidade_vinculada'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examesolicitado',
            name='amostra',
        ),
        migrations.RemoveField(
            model_name='examesolicitado',
            name='requisicao',
        ),
        migrations.RemoveField(
            model_name='examesolicitado',
            name='tecnico_responsavel',
        ),
        migrations.RemoveField(
            model_name='examesolicitado',
            name='tipo_exame',
        ),
        migrations.RemoveField(
            model_name='resultado',
            name='exame_solicitado',
        ),
        migrations.RemoveField(
            model_name='livrosaida',
            name='entregue_por',
        ),
        migrations.RemoveField(
            model_name='livrosaida',
            name='requisicao',
        ),
        migrations.RemoveField(
            model_name='requisicao',
            name='agendamento',
        ),
        migrations.RemoveField(
            model_name='requisicao',
            name='criado_por',
        ),
        migrations.RemoveField(
            model_name='requisicao',
            name='hospital',
        ),
        migrations.RemoveField(
            model_name='requisicao',
            name='medico_solicitante',
        ),
        migrations.RemoveField(
            model_name='requisicao',
            name='paciente',
        ),
        migrations.RemoveField(
            model_name='resultado',
            name='tecnico_responsavel',
        ),
        migrations.RemoveField(
            model_name='resultado',
            name='validado_por',
        ),
        migrations.CreateModel(
            name='SolicitacaoExame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('AGUARDANDO', 'Aguardando Colheita'), ('COLETADO', 'Colhido'), ('EM_ANALISE', 'Em Análise'), ('CONCLUIDO', 'Concluído'), ('CANCELADO', 'Cancelado')], default='AGUARDANDO', max_length=20, verbose_name='Estado')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('atendimento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitacoes_exame', to='App_Atendimentos.atendimento', verbose_name='Atendimento')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitacoes_exame', to='App_Hospital.hospital', verbose_name='Hospital')),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitacoes_exame_emitidas', to=settings.AUTH_USER_MODEL, verbose_name='Médico')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitacoes_exame', to='App_Pacientes.paciente', verbose_name='Paciente')),
            ],
            options={
                'verbose_name': 'Solicitação de Exame',
                'verbose_name_plural': 'Solicitações de Exame',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='ItemSolicitacaoExame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observacoes', models.CharField(blank=True, max_length=255, verbose_name='Observações')),
                ('resultado', models.TextField(blank=True, verbose_name='Resultado')),
                ('data_colheita', models.DateTimeField(blank=True, null=True, verbose_name='Data da colheita')),
                ('data_resultado', models.DateTimeField(blank=True, null=True, verbose_name='Data do resultado')),
                ('tipo_exame', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='itens_solicitados', to='App_Laboratorio.tipoexame', verbose_name='Tipo de Exame')),
                ('solicitacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='App_Laboratorio.solicitacaoexame', verbose_name='Solicitação')),
            ],
            options={
                'verbose_name': 'Item de Solicitação de Exame',
                'verbose_name_plural': 'Itens de Solicitação de Exame',
            },
        ),
        migrations.DeleteModel(
            name='Amostra',
        ),
        migrations.DeleteModel(
            name='ExameSolicitado',
        ),
        migrations.DeleteModel(
            name='LivroSaida',
        ),
        migrations.DeleteModel(
            name='Requisicao',
        ),
        migrations.DeleteModel(
            name='Resultado',
        ),
    ]
