# Generated by Django 6.1 on 2026-08-18 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Laboratorio', '0003_remove_examesolicitado_amostra_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tipoexame',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='tipoexame',
            name='tempo_estimado_horas',
        ),
        migrations.AddField(
            model_name='tipoexame',
            name='codigo_padronizado',
            field=models.CharField(blank=True, help_text='Identificador de padrão externo (ex.: LOINC), quando aplicável', max_length=30, verbose_name='Código Padronizado'),
        ),
        migrations.AddField(
            model_name='tipoexame',
            name='departamento',
            field=models.CharField(choices=[('HEMATOLOGIA', 'Hematologia'), ('BIOQUIMICA', 'Bioquímica'), ('IMUNOLOGIA', 'Imunologia'), ('MICROBIOLOGIA', 'Microbiologia'), ('PARASITOLOGIA', 'Parasitologia'), ('URINALISE', 'Urinálise'), ('COAGULACAO', 'Coagulação'), ('HORMONIOS', 'Hormônios'), ('SEROLOGIA', 'Serologia'), ('GENETICA', 'Genética'), ('ANATOMIA_PATOLOGICA', 'Anatomia Patológica')], default=1, max_length=30, verbose_name='Departamento'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tipoexame',
            name='instrucoes_preparacao',
            field=models.TextField(blank=True, help_text='Orientações ao paciente antes da colheita', verbose_name='Instruções de Preparação'),
        ),
        migrations.AddField(
            model_name='tipoexame',
            name='metodo',
            field=models.CharField(blank=True, choices=[('ESPECTROFOTOMETRIA', 'Espectrofotometria'), ('IMUNOENSAIO', 'Imunoensaio'), ('ELISA', 'ELISA'), ('QUIMIOLUMINESCENCIA', 'Quimioluminescência'), ('ELETROQUIMIOLUMINESCENCIA', 'Eletroquimioluminescência'), ('PCR', 'PCR'), ('MICROSCOPIA', 'Microscopia'), ('CULTURA', 'Cultura'), ('COLORIMETRIA', 'Colorimetria'), ('IMUNOCROMATOGRAFIA', 'Imunocromatografia'), ('POTENCIOMETRIA', 'Potenciometria'), ('TURBIDIMETRIA', 'Turbidimetria'), ('CITOMETRIA_FLUXO', 'Citometria de Fluxo')], max_length=30, verbose_name='Método'),
        ),
        migrations.AddField(
            model_name='tipoexame',
            name='nome_tecnico',
            field=models.CharField(blank=True, help_text='Nome técnico/científico do exame', max_length=150, verbose_name='Nome Técnico'),
        ),
        migrations.AddField(
            model_name='tipoexame',
            name='tempo_estimado',
            field=models.CharField(blank=True, help_text='Ex.: 24 horas, 3 dias', max_length=30, verbose_name='Tempo de Resultado (TAT)'),
        ),
        migrations.AddField(
            model_name='tipoexame',
            name='tipo_resultado',
            field=models.CharField(choices=[('NUMERICO', 'Numérico'), ('QUALITATIVO', 'Qualitativo'), ('MULTIPARAMETRO', 'Multiparâmetro'), ('TEXTO_LIVRE', 'Texto Livre')], default=1, help_text='Define como o resultado será lançado', max_length=20, verbose_name='Tipo de Resultado'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tipoexame',
            name='codigo',
            field=models.CharField(help_text='Identificador único do exame dentro do sistema', max_length=30, unique=True, verbose_name='Código Interno'),
        ),
        migrations.AlterField(
            model_name='tipoexame',
            name='nome',
            field=models.CharField(help_text='Nome comercial/técnico apresentado no sistema', max_length=150, verbose_name='Nome do Exame'),
        ),
        migrations.AlterField(
            model_name='tipoexame',
            name='tipo_amostra',
            field=models.CharField(choices=[('SANGUE', 'Sangue'), ('SORO', 'Soro'), ('PLASMA', 'Plasma'), ('URINA', 'Urina'), ('FEZES', 'Fezes'), ('ESCARRO', 'Escarro'), ('SWAB', 'Swab'), ('SECRECAO', 'Secreção'), ('LCR', 'Líquido Cefalorraquidiano'), ('LIQUIDO_PLEURAL', 'Líquido Pleural'), ('LIQUIDO_ASCITICO', 'Líquido Ascítico'), ('LIQUIDO_SINOVIAL', 'Líquido Sinovial'), ('MEDULA_OSSEA', 'Medula Óssea'), ('TECIDO', 'Tecido')], max_length=30, verbose_name='Tipo de Amostra'),
        ),
        migrations.AlterField(
            model_name='tipoexame',
            name='unidade_medida',
            field=models.CharField(blank=True, help_text='Ex.: mg/dL, g/dL, x10⁹/L', max_length=30, verbose_name='Unidade de Medida'),
        ),
        migrations.AlterField(
            model_name='tipoexame',
            name='valor_referencia',
            field=models.CharField(blank=True, help_text="Ex.: 4.5 - 11.0, ou 'Negativo' para exames qualitativos", max_length=150, verbose_name='Valor de Referência'),
        ),
    ]
