# Generated by Django 6.1 on 2026-08-19 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Laboratorio', '0004_remove_tipoexame_categoria_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parametro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Ex.: HGB', max_length=30, unique=True, verbose_name='Código')),
                ('nome', models.CharField(help_text='Ex.: Hemoglobina', max_length=150, verbose_name='Nome')),
                ('nome_abreviado', models.CharField(blank=True, help_text='Ex.: Hb', max_length=30, verbose_name='Nome Abreviado')),
                ('descricao', models.TextField(blank=True, help_text='Ex.: Concentração de hemoglobina no sangue', verbose_name='Descrição')),
                ('tipo_resultado', models.CharField(choices=[('NUMERICO', 'Numérico'), ('TEXTO', 'Texto'), ('POSITIVO_NEGATIVO', 'Positivo/Negativo'), ('SIM_NAO', 'Sim/Não'), ('OPCOES', 'Opções'), ('TITULO', 'Título'), ('DATA', 'Data'), ('HORA', 'Hora')], max_length=20, verbose_name='Tipo de Resultado')),
                ('unidade', models.CharField(blank=True, help_text='Ex.: g/dL', max_length=30, verbose_name='Unidade')),
                ('casas_decimais', models.PositiveSmallIntegerField(blank=True, help_text='Só relevante para resultados Numéricos. Ex.: 1', null=True, verbose_name='Casas Decimais')),
                ('ativo', models.BooleanField(default=True, verbose_name='Activo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Parâmetro',
                'verbose_name_plural': 'Parâmetros',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='ValorReferencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grupo', models.CharField(default='Adulto', help_text='Ex.: Adulto, Criança, Recém-nascido', max_length=50, verbose_name='Grupo')),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('AMBOS', 'Ambos')], default='AMBOS', max_length=5, verbose_name='Sexo')),
                ('idade_minima', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Idade Mínima (anos)')),
                ('idade_maxima', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Idade Máxima (anos)')),
                ('sinal_minimo', models.CharField(choices=[('>', '>'), ('>=', '>='), ('<', '<'), ('<=', '<='), ('-', '-')], default='-', max_length=2, verbose_name='Sinal Mín.')),
                ('valor_minimo', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Valor Mínimo')),
                ('sinal_maximo', models.CharField(choices=[('>', '>'), ('>=', '>='), ('<', '<'), ('<=', '<='), ('-', '-')], default='-', max_length=2, verbose_name='Sinal Máx.')),
                ('valor_maximo', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Valor Máximo')),
                ('critico_minimo', models.DecimalField(blank=True, decimal_places=3, help_text='Abaixo deste valor, o resultado é sinalizado como crítico', max_digits=10, null=True, verbose_name='Crítico Mínimo')),
                ('critico_maximo', models.DecimalField(blank=True, decimal_places=3, help_text='Acima deste valor, o resultado é sinalizado como crítico', max_digits=10, null=True, verbose_name='Crítico Máximo')),
                ('valor_texto', models.CharField(blank=True, help_text="Ex.: 'Negativo' — usado quando o parâmetro não é numérico", max_length=150, verbose_name='Referência Textual')),
                ('observacoes', models.CharField(blank=True, max_length=255, verbose_name='Observações')),
                ('parametro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valores_referencia', to='App_Laboratorio.parametro', verbose_name='Parâmetro')),
            ],
            options={
                'verbose_name': 'Valor de Referência',
                'verbose_name_plural': 'Valores de Referência',
                'ordering': ['parametro__nome', 'grupo', 'sexo', 'idade_minima'],
            },
        ),
        migrations.CreateModel(
            name='ExameParametro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='Ordem de Exibição')),
                ('subgrupo', models.CharField(blank=True, help_text='Ex.: Série Vermelha, Série Branca — para agrupar parâmetros no laudo', max_length=100, verbose_name='Subgrupo')),
                ('obrigatorio', models.BooleanField(default=True, verbose_name='Obrigatório')),
                ('exibir_no_laudo', models.BooleanField(default=True, verbose_name='Exibir no Laudo')),
                ('permitir_resultado_manual', models.BooleanField(default=True, verbose_name='Permitir Resultado Manual')),
                ('metodo', models.CharField(blank=True, choices=[('ESPECTROFOTOMETRIA', 'Espectrofotometria'), ('IMUNOENSAIO', 'Imunoensaio'), ('ELISA', 'ELISA'), ('QUIMIOLUMINESCENCIA', 'Quimioluminescência'), ('ELETROQUIMIOLUMINESCENCIA', 'Eletroquimioluminescência'), ('PCR', 'PCR'), ('MICROSCOPIA', 'Microscopia'), ('CULTURA', 'Cultura'), ('COLORIMETRIA', 'Colorimetria'), ('IMUNOCROMATOGRAFIA', 'Imunocromatografia'), ('POTENCIOMETRIA', 'Potenciometria'), ('TURBIDIMETRIA', 'Turbidimetria'), ('CITOMETRIA_FLUXO', 'Citometria de Fluxo')], max_length=30, verbose_name='Método (substitui o do Parâmetro, se preenchido)')),
                ('unidade', models.CharField(blank=True, max_length=30, verbose_name='Unidade (substitui a do Parâmetro, se preenchida)')),
                ('tipo_exame', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exame_parametros', to='App_Laboratorio.tipoexame', verbose_name='Tipo de Exame')),
                ('parametro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exame_parametros', to='App_Laboratorio.parametro', verbose_name='Parâmetro')),
            ],
            options={
                'verbose_name': 'Parâmetro do Exame',
                'verbose_name_plural': 'Parâmetros do Exame',
                'ordering': ['tipo_exame__nome', 'ordem'],
                'unique_together': {('tipo_exame', 'parametro')},
            },
        ),
    ]
