# Generated by Django 6.1 on 2026-08-19 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Laboratorio', '0005_parametro_valorreferencia_exameparametro'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultadoParametro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.CharField(blank=True, max_length=255, verbose_name='Valor')),
                ('item_solicitacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultados_parametro', to='App_Laboratorio.itemsolicitacaoexame', verbose_name='Item da Solicitação')),
                ('parametro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='resultados', to='App_Laboratorio.parametro', verbose_name='Parâmetro')),
            ],
            options={
                'verbose_name': 'Resultado de Parâmetro',
                'verbose_name_plural': 'Resultados de Parâmetro',
                'unique_together': {('item_solicitacao', 'parametro')},
            },
        ),
    ]
