# Generated by Django 6.1 on 2026-08-14 08:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('App_Agendamentos', '0001_initial'),
        ('App_Hospital', '0001_initial'),
        ('App_Pacientes', '0003_paciente_entidade_vinculada'),
        ('App_Usuarios', '0002_entidadevinculada'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Atendimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_plano', models.CharField(choices=[('convenio', 'Convênio'), ('particular', 'Particular')], default='particular', max_length=20, verbose_name='Tipo de Plano')),
                ('subtipo_convenio', models.CharField(blank=True, choices=[('empresa', 'Empresa'), ('seguradora', 'Seguradora')], max_length=20, verbose_name='Subtipo de Convénio')),
                ('prioridade', models.CharField(choices=[('Normal', 'Normal'), ('Urgente', 'Urgente'), ('Preferencial', 'Preferencial (Idosos/Gestantes)'), ('Emergência', 'Emergência')], default='Normal', max_length=20, verbose_name='Prioridade')),
                ('tipo_atendimento', models.CharField(choices=[('Consulta Geral', 'Consulta Geral'), ('Especialidade', 'Especialidade Médica'), ('Exames Laboratoriais', 'Exames Laboratoriais'), ('Triagem / Urgência', 'Triagem / Urgência'), ('Retorno', 'Retorno')], max_length=30, verbose_name='Tipo de Atendimento')),
                ('status', models.CharField(choices=[('aguardando', 'Aguardando'), ('em_atendimento', 'Em Atendimento'), ('concluido', 'Concluído'), ('cancelado', 'Cancelado')], default='aguardando', max_length=20, verbose_name='Estado')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('agendamento', models.ForeignKey(blank=True, help_text='Vazio quando o paciente chega directamente, sem marcação prévia.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atendimentos', to='App_Agendamentos.agendamento', verbose_name='Agendamento de origem')),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='atendimentos_criados', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('entidade_vinculada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atendimentos', to='App_Usuarios.entidadevinculada', verbose_name='Entidade Vinculada')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='atendimentos', to='App_Hospital.hospital', verbose_name='Hospital')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='atendimentos', to='App_Pacientes.paciente', verbose_name='Paciente')),
                ('profissional', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='atendimentos', to=settings.AUTH_USER_MODEL, verbose_name='Profissional')),
            ],
            options={
                'verbose_name': 'Atendimento',
                'verbose_name_plural': 'Atendimentos',
                'ordering': ['-criado_em'],
            },
        ),
    ]
