# Generated by Django 6.1 on 2026-08-14 10:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Atendimentos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pressao_arterial', models.CharField(blank=True, help_text='Ex.: 120/80', max_length=15, verbose_name='Pressão Arterial')),
                ('frequencia_cardiaca', models.PositiveIntegerField(blank=True, null=True, verbose_name='Frequência Cardíaca (bpm)')),
                ('frequencia_respiratoria', models.PositiveIntegerField(blank=True, null=True, verbose_name='Frequência Respiratória (irpm)')),
                ('temperatura', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Temperatura (°C)')),
                ('saturacao_o2', models.PositiveIntegerField(blank=True, null=True, verbose_name='Saturação O2 (%)')),
                ('glicemia_capilar', models.PositiveIntegerField(blank=True, null=True, verbose_name='Glicemia Capilar (mg/dL)')),
                ('queixa_historia_atual', models.TextField(blank=True, max_length=2000, verbose_name='Queixa e História Atual')),
                ('exame_fisico', models.TextField(blank=True, max_length=2000, verbose_name='Exame Físico')),
                ('diagnostico_clinico', models.TextField(blank=True, max_length=1000, verbose_name='Diagnóstico Clínico')),
                ('conduta', models.CharField(blank=True, choices=[('SOLICITAR_EXAME', 'Solicitar Exame'), ('INTERNAR', 'Internar'), ('ALTA', 'Alta'), ('PRESCRICAO', 'Prescrição')], max_length=20, verbose_name='Conduta')),
                ('observacoes_condutas', models.TextField(blank=True, max_length=1000, verbose_name='Observações / Condutas Adicionais')),
                ('rascunho', models.BooleanField(default=True, verbose_name='Rascunho')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('atendimento', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='consulta', to='App_Atendimentos.atendimento', verbose_name='Atendimento')),
            ],
            options={
                'verbose_name': 'Consulta',
                'verbose_name_plural': 'Consultas',
            },
        ),
    ]
