# Generated by Django 6.0.7 on 2026-08-07 08:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('App_Hospital', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('codigo', models.CharField(editable=False, max_length=20, unique=True, verbose_name='Código do Paciente')),
                ('numero_processo', models.CharField(editable=False, max_length=30, unique=True, verbose_name='Número do Processo')),
                ('primeiro_nome', models.CharField(max_length=100, verbose_name='Primeiro Nome')),
                ('outros_nomes', models.CharField(blank=True, max_length=150, verbose_name='Outros Nomes')),
                ('ultimo_nome', models.CharField(max_length=100, verbose_name='Apelido')),
                ('nome_social', models.CharField(blank=True, max_length=200, verbose_name='Nome Social')),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=1, verbose_name='Sexo')),
                ('data_nascimento', models.DateField(verbose_name='Data de Nascimento')),
                ('estado_civil', models.CharField(blank=True, choices=[('SOL', 'Solteiro(a)'), ('CAS', 'Casado(a)'), ('DIV', 'Divorciado(a)'), ('VIU', 'Viúvo(a)'), ('UNI', 'União de Facto')], max_length=5, verbose_name='Estado Civil')),
                ('nacionalidade', models.CharField(default='Angolana', max_length=100, verbose_name='Nacionalidade')),
                ('profissao', models.CharField(blank=True, max_length=150, verbose_name='Profissão')),
                ('fotografia', models.ImageField(blank=True, null=True, upload_to='pacientes/', verbose_name='Fotografia')),
                ('estado', models.CharField(choices=[('ATIVO', 'Ativo'), ('INATIVO', 'Inativo'), ('OBITO', 'Óbito'), ('ARQUIVADO', 'Arquivado')], default='ATIVO', max_length=20, verbose_name='Estado')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pacientes', to='App_Hospital.hospital', verbose_name='Hospital')),
            ],
            options={
                'verbose_name': 'Paciente',
                'verbose_name_plural': 'Pacientes',
                'ordering': ['primeiro_nome', 'ultimo_nome'],
            },
        ),
        migrations.CreateModel(
            name='EnderecoPaciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pais', models.CharField(default='Angola', max_length=100, verbose_name='País')),
                ('provincia', models.CharField(max_length=100, verbose_name='Província')),
                ('municipio', models.CharField(max_length=100, verbose_name='Município')),
                ('comuna', models.CharField(blank=True, max_length=100, verbose_name='Comuna')),
                ('bairro', models.CharField(blank=True, max_length=150, verbose_name='Bairro')),
                ('rua', models.CharField(blank=True, max_length=150, verbose_name='Rua')),
                ('numero_casa', models.CharField(blank=True, max_length=20, verbose_name='Número')),
                ('referencia', models.TextField(blank=True, verbose_name='Referência')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('paciente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='endereco', to='App_Pacientes.paciente')),
            ],
            options={
                'verbose_name': 'Endereço',
                'verbose_name_plural': 'Endereços',
            },
        ),
        migrations.CreateModel(
            name='DocumentoPaciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('BI', 'Bilhete de Identidade'), ('PASSAPORTE', 'Passaporte'), ('NIF', 'NIF'), ('CARTAO_RESIDENTE', 'Cartão de Residente'), ('OUTRO', 'Outro')], max_length=30, verbose_name='Tipo')),
                ('numero', models.CharField(max_length=50, verbose_name='Número')),
                ('data_emissao', models.DateField(blank=True, null=True, verbose_name='Data de Emissão')),
                ('data_validade', models.DateField(blank=True, null=True, verbose_name='Data de Validade')),
                ('emitido_por', models.CharField(blank=True, max_length=150, verbose_name='Emitido por')),
                ('principal', models.BooleanField(default=False, verbose_name='Documento Principal')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='App_Pacientes.paciente', verbose_name='Paciente')),
            ],
            options={
                'verbose_name': 'Documento do Paciente',
                'verbose_name_plural': 'Documentos dos Pacientes',
                'ordering': ['tipo'],
            },
        ),
        migrations.CreateModel(
            name='ContactoPaciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('TELEFONE', 'Telefone'), ('TELEMOVEL', 'Telemóvel'), ('EMAIL', 'E-mail'), ('WHATSAPP', 'WhatsApp')], max_length=20)),
                ('contacto', models.CharField(max_length=120)),
                ('principal', models.BooleanField(default=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contactos', to='App_Pacientes.paciente')),
            ],
            options={
                'verbose_name': 'Contacto',
                'verbose_name_plural': 'Contactos',
            },
        ),
        migrations.CreateModel(
            name='ResponsavelPaciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome')),
                ('parentesco', models.CharField(choices=[('PAI', 'Pai'), ('MAE', 'Mãe'), ('CONJUGE', 'Cônjuge'), ('FILHO', 'Filho(a)'), ('IRMAO', 'Irmão(ã)'), ('TIO', 'Tio(a)'), ('AVO', 'Avô/Avó'), ('AMIGO', 'Amigo(a)'), ('OUTRO', 'Outro')], max_length=20, verbose_name='Parentesco')),
                ('telefone', models.CharField(max_length=30, verbose_name='Telefone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail')),
                ('endereco', models.CharField(blank=True, max_length=250, verbose_name='Endereço')),
                ('contacto_emergencia', models.BooleanField(default=False, verbose_name='Contacto de Emergência')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responsaveis', to='App_Pacientes.paciente')),
            ],
            options={
                'verbose_name': 'Responsável',
                'verbose_name_plural': 'Responsáveis',
            },
        ),
    ]
