# Generated by Django 6.1 on 2026-08-13 14:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Pacientes', '0002_perfil_permissao_perfilpermissao'),
        ('App_Usuarios', '0002_entidadevinculada'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='entidade_vinculada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pacientes', to='App_Usuarios.entidadevinculada', verbose_name='Entidade Vinculada'),
        ),
    ]
