# Generated by Django 6.1 on 2026-08-13 09:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('App_Hospital', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=30, unique=True, verbose_name='Código')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome comercial')),
                ('principio_ativo', models.CharField(max_length=150, verbose_name='Princípio activo')),
                ('concentracao', models.CharField(blank=True, help_text='Ex.: 500mg, 250mg/5ml', max_length=50, verbose_name='Concentração')),
                ('forma_farmaceutica', models.CharField(choices=[('COMPRIMIDO', 'Comprimido'), ('CAPSULA', 'Cápsula'), ('XAROPE', 'Xarope'), ('SUSPENSAO', 'Suspensão'), ('INJETAVEL', 'Injetável'), ('POMADA', 'Pomada/Creme'), ('GOTAS', 'Gotas'), ('SUPOSITORIO', 'Supositório'), ('SORO', 'Soro/Solução'), ('OUTRO', 'Outro')], max_length=20, verbose_name='Forma farmacêutica')),
                ('unidade_medida', models.CharField(choices=[('COMPRIMIDO', 'Comprimido'), ('CAPSULA', 'Cápsula'), ('ML', 'Mililitro (ml)'), ('MG', 'Miligrama (mg)'), ('AMPOLA', 'Ampola'), ('FRASCO', 'Frasco'), ('UNIDADE', 'Unidade')], max_length=20, verbose_name='Unidade de medida')),
                ('classe_terapeutica', models.CharField(blank=True, max_length=100, verbose_name='Classe terapêutica')),
                ('controlado', models.BooleanField(default=False, help_text='Requer receita/controlo reforçado (psicotrópicos, entorpecentes, etc.)', verbose_name='Medicamento controlado')),
                ('ativo', models.BooleanField(default=True, verbose_name='Activo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Medicamento',
                'verbose_name_plural': 'Medicamentos',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_lote', models.CharField(max_length=50, verbose_name='Número do lote')),
                ('validade', models.DateField(verbose_name='Data de validade')),
                ('quantidade', models.PositiveIntegerField(default=0, verbose_name='Quantidade disponível')),
                ('fornecedor', models.CharField(blank=True, max_length=150, verbose_name='Fornecedor')),
                ('preco_custo_unitario', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Preço de custo unitário')),
                ('data_entrada', models.DateField(auto_now_add=True, verbose_name='Data de entrada')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lotes_medicamento', to='App_Hospital.hospital', verbose_name='Hospital')),
                ('medicamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lotes', to='App_Farmacia.medicamento', verbose_name='Medicamento')),
            ],
            options={
                'verbose_name': 'Lote',
                'verbose_name_plural': 'Lotes',
                'ordering': ['validade'],
                'unique_together': {('hospital', 'medicamento', 'numero_lote')},
            },
        ),
    ]
