# Generated by Django 6.1 on 2026-08-17 09:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Farmacia', '0001_initial'),
        ('App_Hospital', '0001_initial'),
        ('App_Pacientes', '0003_paciente_entidade_vinculada'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lote',
            name='preco_custo_unitario',
        ),
        migrations.CreateModel(
            name='Dispensacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(verbose_name='Quantidade dispensada')),
                ('observacao', models.CharField(blank=True, max_length=255, verbose_name='Observação')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('farmaceutico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dispensacoes_realizadas', to=settings.AUTH_USER_MODEL, verbose_name='Farmacêutico')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dispensacoes', to='App_Hospital.hospital', verbose_name='Hospital')),
                ('medicamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dispensacoes', to='App_Farmacia.medicamento', verbose_name='Medicamento')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dispensacoes', to='App_Pacientes.paciente', verbose_name='Paciente')),
            ],
            options={
                'verbose_name': 'Dispensação',
                'verbose_name_plural': 'Dispensações',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='ItemDispensacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(verbose_name='Quantidade retirada deste lote')),
                ('dispensacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='App_Farmacia.dispensacao', verbose_name='Dispensação')),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='itens_dispensados', to='App_Farmacia.lote', verbose_name='Lote')),
            ],
            options={
                'verbose_name': 'Item de Dispensação',
                'verbose_name_plural': 'Itens de Dispensação',
            },
        ),
        migrations.CreateModel(
            name='MovimentoStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ENTRADA', 'Entrada'), ('SAIDA', 'Saída'), ('AJUSTE', 'Ajuste')], max_length=10, verbose_name='Tipo')),
                ('quantidade', models.PositiveIntegerField(verbose_name='Quantidade')),
                ('referencia', models.CharField(blank=True, help_text="Ex.: 'Entrada inicial', 'Dispensação #12'", max_length=150, verbose_name='Referência')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimentos', to='App_Farmacia.lote', verbose_name='Lote')),
                ('utilizador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimentos_stock', to=settings.AUTH_USER_MODEL, verbose_name='Utilizador')),
            ],
            options={
                'verbose_name': 'Movimento de Stock',
                'verbose_name_plural': 'Movimentos de Stock',
                'ordering': ['-criado_em'],
            },
        ),
    ]
