# Generated by Django 6.1 on 2026-08-20 12:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Farmacia', '0002_remove_lote_preco_custo_unitario_dispensacao_and_more'),
        ('App_Hospital', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RequisicaoInterna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origem', models.CharField(help_text='Ex.: Nave A - Enfermaria 3, Bloco Operatório', max_length=150, verbose_name='Sector de Origem')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('ENTREGUE', 'Entregue'), ('REJEITADA', 'Rejeitada')], default='PENDENTE', max_length=20, verbose_name='Estado')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requisicoes_internas', to='App_Hospital.hospital', verbose_name='Hospital')),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requisicoes_internas_solicitadas', to=settings.AUTH_USER_MODEL, verbose_name='Solicitante')),
            ],
            options={
                'verbose_name': 'Requisição Interna',
                'verbose_name_plural': 'Requisições Internas',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='ItemRequisicaoInterna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_solicitada', models.PositiveIntegerField(verbose_name='Quantidade Solicitada')),
                ('quantidade_entregue', models.PositiveIntegerField(blank=True, null=True, verbose_name='Quantidade Entregue')),
                ('medicamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='itens_requisitados', to='App_Farmacia.medicamento', verbose_name='Medicamento')),
                ('requisicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='App_Farmacia.requisicaointerna', verbose_name='Requisição')),
            ],
            options={
                'verbose_name': 'Item de Requisição Interna',
                'verbose_name_plural': 'Itens de Requisição Interna',
            },
        ),
    ]
