# Generated by Django 6.1 on 2026-08-13 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntidadeVinculada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome')),
                ('tipo', models.CharField(choices=[('EMPRESA', 'Empresa'), ('SEGURADORA', 'Seguradora'), ('MEDICO', 'Médico'), ('COLABORADOR', 'Colaborador')], max_length=20, verbose_name='Tipo')),
                ('contacto', models.CharField(blank=True, max_length=100, verbose_name='Contacto')),
                ('ativo', models.BooleanField(default=True, verbose_name='Activo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Entidade Vinculada',
                'verbose_name_plural': 'Entidades Vinculadas',
                'ordering': ['nome'],
            },
        ),
    ]
