# Generated by Django 6.0.7 on 2026-08-10 10:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('App_Hospital', '0001_initial'),
        ('App_Pacientes', '0002_perfil_permissao_perfilpermissao'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora', models.DateTimeField(verbose_name='Data e Hora')),
                ('duracao_minutos', models.PositiveIntegerField(default=30, verbose_name='Duração (min)')),
                ('status', models.CharField(choices=[('agendado', 'Agendado'), ('confirmado', 'Confirmado'), ('em_atendimento', 'Em Atendimento'), ('concluido', 'Concluído'), ('cancelado', 'Cancelado'), ('falta', 'Falta')], default='agendado', max_length=20, verbose_name='Status')),
                ('motivo', models.CharField(max_length=200, verbose_name='Motivo')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='agendamentos_criados', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('departamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agendamentos', to='App_Hospital.departamento', verbose_name='Departamento')),
                ('especialidade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agendamentos', to='App_Hospital.especialidade', verbose_name='Especialidade')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='agendamentos', to='App_Hospital.hospital', verbose_name='Hospital')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='agendamentos', to='App_Pacientes.paciente', verbose_name='Paciente')),
                ('profissional', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='agendamentos', to=settings.AUTH_USER_MODEL, verbose_name='Profissional')),
            ],
            options={
                'verbose_name': 'Agendamento',
                'verbose_name_plural': 'Agendamentos',
                'ordering': ['data_hora'],
            },
        ),
    ]
